spring:
  application:
    name: orderServiceApp
  r2dbc:
    url: r2dbc:mysql://localhost:3306/order_service
    username: root
    password: 12345678
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    schemas: public  # Define your schema

server:
  port: 8080

